name: MilkyVote
version: 0.0.1
main: io.github.emckee10.MilkyVote.MVMain
description: Centrilizes Voting
author: TheITx
commands:
  SetVotingSite:
    description: Sets voting website URL
    permission: MilkyVote.SetVotingSite
    permission-message: You do not have the permission to use this command.
    usage: "&cUsage: /<command> [URL]"
    aliases: [setURL]
  MilkyVote:
    description: displays voting URL
    aliases: [milkvote, mvote]
    usage: "&cUsage: /<command>"

