name: MilkyVote
version: 0.0.1
main: io.github.emckee10.MilkyVote.MVMain
description: Centrilizes Voting
author: TheITx
commands:
  SetVotingSite:
    description: Sets voting website URL
    aliases: seturl
    permission: MilkyVote.SetVoting
    permission-message: You do not have the permission to use this command.
    usage: "Usage: /<command> [URL]"
  SetVotingDisplayMessage:
    description: Sets the message that will disguise your URL
    aliases: setdisplaymessage
    permission: MilkyVote.SetVoting
    permission-message: You do not have the permission to use this command.
    usage: "Usage:/<command> [DisplayMessage]"
  MilkyVote:
    description: Displays voting URL
    aliases: mvote
    usage: "Usage: /<command>"

